package jorge.veamurguia.entidad;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Almacen.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//


import java.util.Hashtable;

public class Almacen {
	public int ID;
	public Hashtable<Articulo,Integer> Articulos;//articulo cantidad 
	
	public Almacen(){
		Articulos =new Hashtable<Articulo, Integer>();
	}
	public void Listar() {
	
	}
}
