package jorge.veamurguia.entidad;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Articulo.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//




public class Articulo {
	public Integer ID;
	public String Articulo;
	public String Codigo;
	public Categoria ID_Categoria;
	public Float precio;
	
}
