package jorge.veamurguia.entidad;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Categoria.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamurguia@gmail.com
//




public class Categoria {
	public Integer ID;
	public String Categoria;
}
