package jorge.veamurguia.entidad;
import java.util.Comparator;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//




public class Cliente  {
	public String DNI;
	public String Nombre;
	public String Apellidos;
	public String Direccion;
	public Integer ID;
	public void Comprar(Venta venta) {
	
	}
	
	public void Devolver(Venta venta) {
	
	}
	
	public void imprimirCarnet() {
	
	}

	
}
