package jorge.veamurguia.entidad;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Compra.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//



import java.util.Date;
import java.util.Vector;

public class Compra {
	public int ID;
	public Vector<LineaCompra> Lineas;
	public Date Fecha;
	public Personal ID_Personal;
	public Proveedor ID_Proveedor;
	public float Precio;
	public int Cantidad;
	public void crear( LineaCompra lineaCompra) {
	
	}
	
	public Vector<LineaCompra> buscar( LineaCompra lineaCompra) {
		return null;
	
	}
	
	public void modificar( LineaCompra lineaCompra) {
	
	}
	
	public void Listar() {
	
	}
	
	public void borrar( LineaCompra lineaCompra) {
	
	}
}
