package jorge.veamurguia.entidad;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LineaVenta.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//




public class LineaVenta {
	public Integer ID;
	public Venta ID_Venta;
	public Articulo ID_Articulo;
	public Float Precio;
	public Float Descuento;
	public Integer Cantidad;
	public Float Impuesto;	
}
