package jorge.veamurguia.entidad;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LineaPedido.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//




public class LineaPedido {
	public int ID;
	public Pedido ID_Pedido;
	public Articulo ID_Articulo;
	public float Precio;
	public int Cantidad;
	public float Total;
}
