package jorge.veamurguia.entidad;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LineaCompra.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//




public class LineaCompra {
	public int ID;
	public Compra ID_Compra;
	public Articulo ID_Articulo;
	public float Precio;
	public float Cantidad;
}
