package jorge.veamurguia.entidad;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pedido.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//



import java.util.Date;
import java.util.Vector;

public class Pedido {
	public int ID;
	public Vector<LineaPedido> lineas;
	public Date Fecha;
	public Personal ID_Personal;
	public Proveedor ID_Proveedor;
	public float Precio;
	public int Cantidad;
	public Pedido(){
		lineas= new Vector<LineaPedido>(); 
		
	}
	public void crear( LineaPedido lineaPedido) {
	
	}
	
	public Vector<LineaPedido> buscar(LineaPedido lineaPedido) {
			return null;
	
	}
	
	public void modificar( LineaPedido lineaPedido) {
	
	}
	
	public void Listar() {
		System.out.println("##############################################");
		System.out.println("Pedido ID:"+ID +"realizado por "+ID_Personal.Nombre);
		System.out.println("proveedor ID:"+ID_Proveedor.Proveedor );

		
		this.Precio=0;
		this.Cantidad=0;
		
		for(LineaPedido linea: lineas){
			
			linea.Total=linea.Cantidad*linea.Precio;
			this.Precio=this.Precio+linea.Total;
			
			this.Cantidad=this.Cantidad+linea.Cantidad;
			System.out.println("------------------------------------------------------------------------------------");
			System.out.println("Codigo Articulo "+linea.ID_Articulo.Codigo +" Descripcion:"+linea.ID_Articulo.Articulo);
			System.out.println("linea :"+linea.ID+" | "+linea.Precio+" X "+linea.Cantidad +" = "+linea.Total);
		}
		System.out.println("------------------------------------------------------------------------------------");
		System.out.println("Total de articulos :"+this.Cantidad+" precio "+this.Precio);
		
	}
	
	public void borrar(LineaPedido lineaPedido) {
	
	}
}
