package jorge.veamurguia.entidad;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Venta.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//




public class Venta {
	public Integer ID;
	public String Fecha;
	public Personal ID_Personal;
	public Cliente ID_Cliente;
	public Float Precio;
}
