/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AutorGui.java
 *
 * Created on 13-abr-2010, 1:10:35
 */

package jorge.veamurguia.gui;

/**
 *
 * @author jorge
 */
public class AutorGui extends javax.swing.JFrame {

    /** Creates new form AutorGui */
    public AutorGui() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(10, 0));

        jLabel1.setText("Autor: ");
        getContentPane().add(jLabel1);

        jLabel2.setText("D.N.I.. ");
        getContentPane().add(jLabel2);

        jLabel3.setText("direccion:);
        getContentPane().add(jLabel3);

        jLabel4.setText("teléfono: \\ ");
        getContentPane().add(jLabel4);

        jLabel5.setText("Correo: ");
        getContentPane().add(jLabel5);

        jLabel6.setText("CA: Calatayud");
        getContentPane().add(jLabel6);

        jLabel7.setText("Expediente");
        getContentPane().add(jLabel7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutorGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

}
