package jorge.veamurguia.gestor;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionCompra.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//


import java.util.Vector;

import jorge.veamurguia.entidad.Compra;
import jorge.veamurguia.entidad.Venta;


public class GestionCompra {
	public Vector<Compra> Compras;
	
	public void crear(Compra compra) {
	
	}
	
	public Vector<Venta> buscar( Compra compra) {
		return null;
	
	}
	
	public void modificar( Compra compra) {
	
	}
	
	public void borrar( Compra compra) {
	
	}
}
