package jorge.veamurguia.gestor;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionVenta.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//


import java.util.Vector;

import jorge.veamurguia.entidad.Venta;


public class GestionVenta {
	public Vector<Venta> Ventas;
	public void crear(Venta venta) {
	
	}
	
	public Vector <Venta> buscar( Venta venta) {
		return null;
	
	}
	
	public void modificar(Venta venta) {
	
	}
	
	public void borrar( Venta venta) {
	
	}
}
