package jorge.veamurguia.gestor;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionPersonal.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//


import java.util.Vector	;

import jorge.veamurguia.entidad.Personal;

public class GestionPersonal {
	public Vector<Personal> Personales;

	public void crear( Personal personal) {
	
	}
	
	public Vector<Personal> buscar( Personal personal) {
		return null;
	
	}
	
	public void modificar( Personal personal) {
	
	}
	
	public void borrar( Personal personal) {
	
	}
}
