package jorge.veamurguia.gestor;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionProveedores.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//


import java.util.Vector;

import jorge.veamurguia.entidad.Proveedor;


public class GestionProveedores {
	
	public Vector<Proveedor> Proveedores;

	public void crear( Proveedor proveedor) {
	
	}
	
	public void buscar() {
	
	}
	
	public void modificar() {
	
	}
	
	public void borrar() {
	
	}
}
