package jorge.veamurguia.gestor;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionPedido.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//


import java.util.Vector;

import jorge.veamurguia.entidad.Pedido;

public class GestionPedido {
	public Vector<Pedido> Pedidos;
	public void crear( Pedido pedido) {
	
	}
	
	public Vector<Pedido> buscar( Pedido pedido) {
		return null;
	
	}
	
	public void modificar( Pedido pedido) {
	
	}
	
	public void borrar( Pedido pedido) {
		}
}
