package jorge.veamurguia.gestor;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionVentas.java
//  @ Date : 01/03/2010
//  @ Author :jorge.veamurguia
//  @email:jorge.veamruguia@gmail.com
//



import java.util.Vector;

import jorge.veamurguia.entidad.Venta;


public class GestionVentas {
	public Vector<Venta> Ventas;
	public void crear() {
	
	}
	
	public void buscar() {
	
	}
	
	public void modificar() {
	
	}
	
	public void borrar() {
	
	}
}
